### PR TITLE
To gradle

### PR DESCRIPTION
**Pull request by kevinvandenbreemen**
Switch to the Gradle build system.  Use Kotlin scripting language flavour of Gradle

### CODE REVIEW

**Comment by RoganDawes** [comment]
Hi Kevin,

I appreciate your PR, and am glad that you find WebScarab to be useful after so many years of neglect on my part.

Unfortunately, I have no knowledge of the Gradle build system, nor (to be frank) much motivation to learn it at this point. There seems little point in accepting a PR that adds functionality that I won't be able to maintain (to a project that I am not maintaining anyway).

**Comment by kevinvandenbreemen** [comment]
> Hi Kevin,
> 
> I appreciate your PR, and am glad that you find WebScarab to be useful after so many years of neglect on my part.
> 
> Unfortunately, I have no knowledge of the Gradle build system, nor (to be frank) much motivation to learn it at this point. There seems little point in accepting a PR that adds functionality that I won't be able to maintain (to a project that I am not maintaining anyway).

Hi there,  
I appreciate your time and your frankness about this PR.  

Are you or your team / OWASP building/maintaining a newer open source proxy?  I have been occasionally trying to revitalize Webscarab and get it working with HTTPS again but if you have a newer open source alternative I would love to try it out.

**Comment by RoganDawes** [comment]
I did create an updated WebScarab-NG based on the Spring Rich Client Platform and Spring framework, but it never really went anywhere. There were a couple of ideas in there that I really like(d), such as the "stays on top" window where you can comment on the next request to pass through the proxy, or turn intercept on and off. But Spring RCP died due to lack of interest/maintenance, and so did WS-NG.
At this point, the OWASP-blessed proxy is ZAP, but I have no connection to it at all.

**Comment by davewichers** [comment]
@kevinvandenbreemen - What? Does OWASP have another proxy??? :-).  OWASP ZAP is like OWASP's biggest project: https://github.com/zaproxy/zaproxy.  @psiinon - Thought you might find that question amusing :-). And Kevin, not trying to throw you under a bus.

**Comment by kevinvandenbreemen** [comment]
> @kevinvandenbreemen - What? Does OWASP have another proxy??? :-). OWASP ZAP is like OWASP's biggest project: https://github.com/zaproxy/zaproxy. @psiinon - Thought you might find that question amusing :-). And Kevin, not trying to throw you under a bus.

Hey there,
Touche, lol.
I saw ZAP but to be honest it looked like it was for pen testing more than for generic purposes.  Could I use it out of the box to do benign things such looking at request/response payloads to restful services / websites?

**Comment by psiinon** [comment]
@kevinvandenbreemen of course - I used to use it as a debugging tool when I worked on web apps. You can put it in "safe" mode if you want to make sure it will not make any changes to the traffic, or you can use it to manipulate traffic manually - you dont have to just use it for malicious payloads ;)

**Comment by psiinon** [comment]
FYI ZAP is very community focussed - if you would like to get involved then just let me know. You can work on any features you want so if you want to make it better for QA or anything else then thats definitely not a problem :)

**Pull request closed without merging**
